### ISSUE TITLE
ConnectionEndPoint specification - Modeling Issue

### ISSUE THREAD

**Issue by rszwedowski** [OpenNetworkingFoundation/TAPI#106]
Hey guys, 
[Sorry if its wrong place for leaving the comments (->IMP Call?)]
I'm "compiling" the ConnectivityService YANG spec and found something which makes me wonder. Why ConnectionEndPoint is considered as a Resource (uses ResourceSpec) - in as a result this object inherit uuid, which has no sense (?) as long the _connectionEndPoint is container (not list) - am I wrong?

Greetings, 
Rafał Szwedowski

**Comment by karthik-sethuraman** [comment]
Related to #131

**Comment by karthik-sethuraman** [comment]
This issue will be tracked as part of #131 discussion

**Comment by amazzini** [comment]
This issue has been closed due to the lack of activity for more than one year.
Please reopen it if follow up is necessary.
