### ISSUE TITLE
Should connectionEndPoint in Connection Class be references or instances?

### ISSUE THREAD

**Issue by HuiDingCATR** [OpenNetworkingFoundation/TAPI#131]
In current connectivityService.yang, _connectionEndPoint in Connection are array of instances. Maybe they should be references to make the operation of getConnectionDetails more efficient and the operation of getConnectionEndPointDetails makes sense.

**Comment by karthik-sethuraman** [comment]
Related Issue #106

**Comment by amazzini** [comment]
This issue has been closed due to the lack of activity for more than one year.
Please reopen it if follow up is necessary.
