### ISSUE TITLE
remove serviceIdOrName for getConnectionDetails operation

### ISSUE THREAD

**Issue by HuiDingCATR** [OpenNetworkingFoundation/TAPI#132]
The input parameters for getConnectionDetails are serviceIdOrName and connectionIdOrName, since Connection is a global class with universal unique ID, maybe only connectionIdOrName is enough.

**Comment by karthik-sethuraman** [comment]
Related discussion #115

**Comment by HuiDingCATR** [comment]
Understand now.

**Comment by karthik-sethuraman** [comment]
Let us keep this open until we resolve #115 . Either way, the behavior between RPC and SCRUD flavors of RESTConf mapping should be consistent.

**Comment by karthik-sethuraman** [comment]
This issue will be tracked as part of #151 discussion

**Comment by amazzini** [comment]
This issue has been closed due to the lack of activity for more than one year.
Please reopen it if follow up is necessary.
