### ISSUE TITLE
RI: Clarification about layerProtocolName in Topology

### ISSUE THREAD

**Issue by italobusi** [OpenNetworkingFoundation/TAPI#146]
As a follow up of #145 , assuming that NEPs and Nodes have only one layer protocol, since Nodes and NEPs with different layer protocols can co-exist in the same topology, the layerProtocolName should have cardinality of [1..*].

However, what is the relationship between the layerProtocolName of the Topology object class and of the other classes? It is the superset?

In the RI:
`
                "layerProtocolName": [
                    "OCH"
                ],
                "uuid": "top0"
`

What does it mean?

What would have been the differences with respect to these cases:

a) ETH

`
                "layerProtocolName": [
                    "ETH"
                ],
`

b) ETH+OCH

`
                "layerProtocolName": [
                    "ETH"
                    "OCH"
                ],
`

c) OCH+ETH

`
                "layerProtocolName": [
                    "OCH"
                    "ETH"
                ],
`

d) ODU

`
                "layerProtocolName": [
                    "ODU"
                ],
`

**Comment by karthik-sethuraman** [comment]
The layerProtocolName in the Topology is expected to be a super-set of all the encompassed Node/Link layerProtocolNames.

**Comment by italobusi** [comment]
**Notes from the T-API call (January 10, 2017):**

We have agreed to clarify that the layerProtocolName of the Topology object class is expected to be a super-set of all the encompassed Node/Link layerProtocolNames

@karthik-sethuraman : please update UML descriptions

**Comment by amazzini** [comment]
This issue has been closed due to the lack of activity for more than one year.
Please reopen it if follow up is necessary.
