### ISSUE TITLE
RPC call to retrieve calculated path by UUID is missing.

### ISSUE THREAD

**Issue by pavellikin** [OpenNetworkingFoundation/TAPI#161]
Hi,

From restconf description it is possible to retrieve previously calculated paths. For that it is needed to send GET request to the following URL `/config/Context/_path/{uuid}/`.
Unfortunately such mechanism is missing for RPC calls. Could you please add `GetP2PPathRPCInputSchema` and `GetP2PPathRPCOutputSchema` with `Path` entity inside?

**Comment by amazzini** [comment]
RPCs are out of the scope of TAPI.
