### ISSUE TITLE
Specify valid Name Types for ServiceInterfacePoint

### ISSUE THREAD

**Issue by karthik-sethuraman** [OpenNetworkingFoundation/TAPI#190]
In TAPI, the NameAndValue is currently being used as "KeyAndValue" - the valueName attribute of the data-type is specified to be object key.
- So it would make sense to refactor the attribute "valueName" to "nameType"
- Make the type of "key" attribute to be an extensible enumeration  NameType
- use the following initial values for the NameType enum - [IPV4, IPV6, MAC, TNA, LFID, LABEL, TID, TE_ID, NODEID]

**Comment by karthik-sethuraman** [comment]
**_TAPI Call 6/6/2017: _** - Noted that since this is a _common data type_ used by all TAPI classes, the valid/applicable list of enum literals would be constrained by the usage (specific to class type it is being applied). We may need to create specific typedefs, e.g. **NodeNameType**, **ServiceInterfacePointNameType**, etc

**Comment by amazzini** [comment]
This issue has been closed due to the lack of activity for more than one year.
Please reopen it if follow up is necessary.
