### ISSUE TITLE
Requirement for Retrieving the Connections in a Node

### ISSUE THREAD

**Issue by RodLU** [OpenNetworkingFoundation/TAPI#218]
There is only one association ConnectionIsContainedByNode between the Node and Conneciton, which means we can not retrieve all the Connections of one Node. Is it possible to add a operation to make it happen, although it might break the decoupling, can anybody figure out a way?

**Comment by amazzini** [comment]
This issue has been closed due to the lack of activity for more than one year.
Please reopen it if follow up is necessary.
