### ISSUE TITLE
Multiplicity of layerProtocolName of ConnectivityService

### ISSUE THREAD

**Issue by RodLU** [OpenNetworkingFoundation/TAPI#228]
It is unclear of the meaning of layerProtocolName in ConnectivityService. If one end of a ConnectivityService is ETH, and the other end is ODU, it's unclear the layerProtocolName of this  ConnectivityService is ETH or ODU. It's proposed to change the multiplicity of this attribute from '1' to '*'.

**Comment by amazzini** [comment]
This issue has been closed due to the lack of activity for more than one year.
Please reopen it if follow up is necessary.
