### ISSUE TITLE
Connection End Point of Route

### ISSUE THREAD

**Issue by RodLU** [OpenNetworkingFoundation/TAPI#237]
There is a requirement to look into the details of ConnectionEndPoint of a Route, like tributary slot information of CEP. But the CEP list of Route entity is a reference. It's hard to retrieve the details of CEPs by using their UUIDs. It would be better to have a interface to retrieve all the CEPs' information by the IDs of a Route and a Connection as input.

**Comment by amazzini** [comment]
This issue has been closed due to the lack of activity for more than one year.
Please reopen it if follow up is necessary.
