### ISSUE TITLE
tapi-notification.yang: inconsistent descriptions

### ISSUE THREAD

**Issue by GermanoSMO** [OpenNetworkingFoundation/TAPI#259]
There are inconsistent/meaningless descriptions in the tapi-notification.yang module:

An example is the notification-type (Line 246 and following):
The descriptions for the OBJECT_CREATION enumerated value and for the notification type itself are not  meaningul and refer to something into a totally different scope:

        typedef notification-type {
            type enumeration {
                enum OBJECT_CREATION {
              --->description "Not a normal state. The system is unable to determine the correct value.";**
                }
                enum OBJECT_DELETION {
                    description "none";
                }
                enum ATTRIBUTE_VALUE_CHANGE {
                    description "none";
                }
                enum ALARM_EVENT {
                    description "none";
                }
                enum THRESHOLD_CROSSING_ALERT {
                    description "none";
                }
            }
        --->description "The orientation of flow at the Port of a Forwarding entity";

The same for the description of the object-type (line 266 and following):
        typedef object-type {
            type enumeration {
             ......
             }
        --->description "The orientation of flow at the Port of a Forwarding entity";
        }

**Comment by amazzini** [comment]
This issue has been closed due to the lack of activity for more than one year.
Please reopen it if follow up is necessary.
