### ISSUE TITLE
Creation of ServiceInterfacePoint

### ISSUE THREAD

**Issue by italobusi** [OpenNetworkingFoundation/TAPI#260]
As reported in TAPI 1.0 FRS (TR-527):

> Service EndPoints, representing shared knowledge between the customer and the provider, needs to be pre-configured, based on customer and provider negotiation

I cannot find any UML stereotype indicating that the instances of ServiceInterfacePoint cannot be created, but in the YANG model the list of SIPs is marked as rw:

` +--rw service-interface-point* [uuid]`

I have also noted that the writeAllowed stereotype for uuid and name attributes of the are CREATE_AND_UPDATE. I think they should be WRITE_NOT_ALLOWED.

**Comment by karthik-sethuraman** [comment]
- Will update the UML model with appropriate *writeAllowed* stereotype value
- The Eagle uml2yang tool does not use the UML Profile *writeAllowed* stereotype for now, but may use in future. 
- SIP in curent TAPI release is intended to be updatable/editable, hence Yang config=true. AIFK Yang does not support update-only-but-not-create. 
- Agree that *uuid* should be readOnly in general, but YANG requires key-attributes of "configurable" clases to be writable.
- *name* attribute is intended to be writable.

**Comment by bzeuner** [comment]
Regarding creation of SIP:
If there is no operation defined to create a SIP, there is no way to create a SIP.

Regarding YANG config:
true is default.

Regarding uuid:
From the Mapping Guidelines "_Attributes marked as “partOfObjectKey” must be mapped as read/write attributes, even when marked as WRITE_NOT_ALLOWED._"

**Comment by amazzini** [comment]
This issue has been closed due to the lack of activity for more than one year.
Please reopen it if follow up is necessary.
