### ISSUE TITLE
UML writeAllowed stereotype for ServiceInterfacePoint:LayerProtocolName

### ISSUE THREAD

**Issue by italobusi** [OpenNetworkingFoundation/TAPI#261]
The writeAllowed stereotype for this attribute is CREATE_AND_UPDATE

However, as indicated in open issue #260 , since SIPs are shared knowledge, I think the stereotype should be WRITE_NOT_ALLOWED

It is worth noting that the YANG model is correct:

`|  +--ro layer-protocol-name*        layer-protocol-name`

It is not clear how the YANG tool has properly marked this list as read-only even if the UML writeAllowed stereotype was CREATE_AND_UPDATE

**Comment by amazzini** [comment]
This issue has been closed due to the lack of activity for more than one year.
Please reopen it if follow up is necessary.
