### ISSUE TITLE
UML lifecycleState stereotype for ServiceInterfacePoint:LayerProtocolName

### ISSUE THREAD

**Issue by italobusi** [OpenNetworkingFoundation/TAPI#262]
I cannot find this UML stereotype indicating the maturity level of this attribute (section 6.2.1 of TR-514)

I am not sure we can consider this attribute as "Mature" considering the following description

> Usage of layerProtocolName [>1]  in the ServiceInterfacePoint should be considered experimental

Should we qualify this attribute as preliminary?

**Comment by italobusi** [comment]
See generic open issue #263

**Comment by karthik-sethuraman** [comment]
Notes from the 12/27 ad-hoc call to resolve TAPI 2.0 last-call comments
- Update the UML model attribute *layerProtocolName* with the UML *\<\<Preliminary\>\>* stereotype

**Comment by amazzini** [comment]
This issue has been closed due to the lack of activity for more than one year.
Please reopen it if follow up is necessary.
