### ISSUE TITLE
Extensible Enumeration

### ISSUE THREAD

**Issue by italobusi** [OpenNetworkingFoundation/TAPI#264]
It seems that many enumerations are not properly marked as extensible and translated as YANG enumeration instead of YANG identity

This issue is also discussed in section 6 of:
https://tools.ietf.org/html/draft-bryskin-teas-yang-ietf-vs-onf-01

It has also been discussed in previous ONF meetings and, at that time, it has been recognized that using YANG enumerations would lead to backward compatibility issues when the enumeration is extended.

More specific comments/issues will be opened but this seems a quite generic comment applicable to the whole TAPI enumerations

**Comment by amazzini** [comment]
This issue has been closed due to the lack of activity for more than one year.
Please reopen it if follow up is necessary.
