### ISSUE TITLE
Extensibility and UML lifecycleState stereotype for the LifecycleState DataType

### ISSUE THREAD

**Issue by italobusi** [OpenNetworkingFoundation/TAPI#265]
It seems that this DataType definition is not fully stable and, as a consequence, also the enumeration should be extensible: see comments #263 and #264 

During the May meeting, it appeared that the values and state transitions can be different for different object and the following diagram has been prepared for TapiConnectivityService:

![lifecycle states](https://user-images.githubusercontent.com/12461741/34119282-dde01d3a-e421-11e7-8ab6-29a8e3e0633e.png)

The value POTENTIAL exists TAPI UML but not on this diagram.

During the November meeting, some further work has been done by OIMT in oimt2017.MB.001:

https://wiki.opennetworking.org/download/attachments/271777805/oimt2017.MB.001.01.entity-lifecycle.docx?version=1&modificationDate=1513359517000&api=v2

In this document, the value POTENTIAL does not exist but the values PotentialAvailable and PotentialBusy exist.

**Comment by karthik-sethuraman** [comment]
Notes from the 12/27 ad-hoc call to resolve TAPI 2.0 last-call comments
- Update the UML model Enum/Datatype *LifecycleState* with the UML *\<\<Preliminary\>\>* stereotype
- Replace *POTENTIAL* with *POTENTIAL_AVAILABLE* and *POTENTIAL_BUSY* values (discussed previously in the F2F meeting)
- The specific proposal to make this extensible needs be discussed in TAPI/CoreIM call (deferred to 2.1.0)
- Need to consider the Entity-Lifecycle model contribution by Malcolm in Core IM, when discussing the proposal to make this enumeration extensible (deferred to 2.1.0)

**Comment by italobusi** [comment]
@karthik-sethuraman : this issue has been closed but I do not recall any conclusion for the last two actions pending from TAPI 2.0 last-call comments resolution:

> - The specific proposal to make this extensible needs be discussed in TAPI/CoreIM call (deferred to 2.1.0)
> - Need to consider the Entity-Lifecycle model contribution by Malcolm in Core IM, when discussing the proposal to make this enumeration extensible (deferred to 2.1.0)
> 

Moreover, I have noticed that in the current UML model, everything is marked as `<<Experimental>>` but the `POTENTIAL_BUSY` value. Should also this value be marked as `<<Experimental>>`?
