### ISSUE TITLE
Directionality information

### ISSUE THREAD

**Issue by italobusi** [OpenNetworkingFoundation/TAPI#266]
It seems that ForwardingDirection, TerminationDirection and PortDirection provide redundand information to control unidirectional and bidirectional forwarding

Most of the use cases analysed so far have been assuming all the forwarding was bidirectional

It is proposed to consider these DataTypes (as well as all the attributes using them) as Experimental: see comment #263

**Comment by karthik-sethuraman** [comment]
Notes from the 12/27 ad-hoc call to resolve TAPI 2.0 last-call comments
- Update the UML model Enum/Datatype/Pac and related attributes for *TerminationDirection* with the UML *\<\<Experimental\>\>* stereotype
- Develop example(s) that depict bidirectional forwarding terminating on pair of uni-directional ports/ends (deferred to 2.1.0)

**Comment by italobusi** [comment]
@karthik-sethuraman : this issue has been closed but:
- The ForwardingDirection, TerminationDirection and PortDirection are not yet marked with any UML stereotype (assuming they are considered mature)
- moreover I do not recall any conclusion for the action pending from TAPI 2.0 last-call comments resolution:

> - Develop example(s) that depict bidirectional forwarding terminating on pair of uni-directional ports/ends (deferred to 2.1.0)
