### ISSUE TITLE
OCH LayerProtocolName

### ISSUE THREAD

**Issue by italobusi** [OpenNetworkingFoundation/TAPI#267]
The OCH value has been removed from the LayerProtocolName and replaced with OTSiA

However, it seems that OCH and OTSiA are not the same and most of the existing implementations support only OCH

It is proposed to add OCH to the LayerProtocolName  enumeration

**Comment by karthik-sethuraman** [comment]
Notes from the 12/27 ad-hoc call to resolve TAPI 2.0 last-call comments
- Update the UML model Enum/Datatype *LayerprotocolName* with additional enumeration value *OCH*
- Request clarification from SG15 on the most up-to-date use of the *OTSi & OCH* layer-rates (deferred to 2.1.0)
