### ISSUE TITLE
ETY LayerProtocolName

### ISSUE THREAD

**Issue by italobusi** [OpenNetworkingFoundation/TAPI#268]
ETY is not a layer network

Most of the ETY specific attributes are defined by IEEE 802.3 YANG models and there are no corresponding UML definitions

It is also not clear what are the use cases to control ETY attributes using TAPI

It is proposed to remove ETY from the LayerProtocolName enumeration

**Comment by karthik-sethuraman** [comment]
Fixed by PR #324
