### ISSUE TITLE
Extensibility and UML lifecycleState stereotype for the LayerProtocolName enumeration

### ISSUE THREAD

**Issue by italobusi** [OpenNetworkingFoundation/TAPI#269]
It seems that this enumeration should be extensible to allow control of new layer protocols not yet defined: see open issue #264 

As discussed in open issues #267 and #268 , this enumeration is not fully stable.

However, some values are stable and mature (e.g., ODU and ETH).

Is there a way to qualify different maturity levels for different values of this Enumeration?

**Comment by amazzini** [comment]
This issue has been closed due to the lack of activity for more than one year.
Please reopen it if follow up is necessary.
