### ISSUE TITLE
Clarification about the DirectiveValue Enumeration

### ISSUE THREAD

**Issue by italobusi** [OpenNetworkingFoundation/TAPI#271]
This enumeration is not clear and related UML descriptions seem to be empty

Is this enumeration extensible? See open issue #264 

I would propose to mark this DataType as Experimental: see open issue #263

**Comment by karthik-sethuraman** [comment]
Notes from the 12/27 ad-hoc call to resolve TAPI 2.0 last-call comments
- Update the UML model Enum/Datatype *DirectiveValue* with the UML *\<\<Experimental\>\>* stereotype
- The specific proposal to make this extensible needs be discussed in TAPI/CoreIM call (deferred to 2.1.0)
- Need update UML comment/description field (deferred to 2.0.1)

**Comment by italobusi** [comment]
@karthik-sethuraman : this issue has been closed but I do not recall any conclusion for the last two actions pending from TAPI 2.0 last-call comments resolution:

> - The specific proposal to make this extensible needs be discussed in TAPI/CoreIM call (deferred to 2.1.0)
> - Need update UML comment/description field (deferred to 2.0.1)

Moreover, the UML description seems still empty in the TAPI develop branch
