### ISSUE TITLE
TerminationState Enumeration

### ISSUE THREAD

**Issue by italobusi** [OpenNetworkingFoundation/TAPI#272]
I am not sure we really need this enumeration

There has been a lot of discussion in the past months about how to model some "special" cases with lack of flexibility  but no conclusion has been reached

The LP Spec has also been split into CtpPac, TtpPac (or TerminationPac and ClientAdaptationPac, not sure what option has been selected in RC3): these packages can be sufficient to qualify a CEP as a CTP, a TTP or a combined CTP+TTP

I would mark this enumeration as Experimental: see open issue #263

**Comment by karthik-sethuraman** [comment]
Notes from the 12/27 ad-hoc call to resolve TAPI 2.0 last-call comments
- Update the UML model Enum/Datatype/Pac and related attributes for *TerminationState* with the UML *\<\<Experimental\>\>* stereotype
- Develop example(s) that depict the usage of termination-state (deferred to 2.1.0)

**Comment by italobusi** [comment]
@karthik-sethuraman : this issue has been closed but I do not recall any conclusion for the action pending from TAPI 2.0 last-call comments resolution:

> - Develop example(s) that depict the usage of termination-state (deferred to 2.1.0)
