### ISSUE TITLE
Make the Capacity DataType simpler to support technology-specific definitions

### ISSUE THREAD

**Issue by italobusi** [OpenNetworkingFoundation/TAPI#275]
The current definition of the Capacity DataType seems too restrictive/complex for some technologies (e.g., OTN).

Within OTN it is preferable to describe the total/available capacity in terms of number of ODUs that can be setup for a given time.

IETF TEAS is taking an interesting approach in defining capacity (bandwidth) attributes in a generic way while allowing technology-specific experts to specify the definitions for each technology:

https://tools.ietf.org/html/draft-ietf-teas-yang-te-topo-13

```
                   +--rw max-link-bandwidth
                   |  +--rw te-bandwidth
                   |     +--rw (technology)?
                   |        +--:(psc)
                   |        |  +--rw psc?       rt-types:bandwidth-ieee-
   float32
                   |        +--:(otn)
                   |        |  +--rw otn* [rate-type]
                   |        |     +--rw rate-type    identityref
                   |        |     +--rw counter?     uint16
                   |        +--:(lsc)
                   |        |  +--rw wdm* [spectrum slot]
                   |        |     +--rw spectrum    identityref
                   |        |     +--rw slot        int16
                   |        |     +--rw width?      uint16
                   |        +--:(generic)
                   |           +--rw generic?   te-bandwidth
```

I would suggest evaluating this approach also within TAPI

**Comment by amazzini** [comment]
This issue has been closed due to the lack of activity for more than one year.
Please reopen it if follow up is necessary.
