### ISSUE TITLE
Incorrect type for the Burst Size in the BandwidthProfile DataType

### ISSUE THREAD

**Issue by italobusi** [OpenNetworkingFoundation/TAPI#276]
The peakBurstSize and committedBurstSize are defined with the CapacityValue DataType

However, as opposed to rates, burst sizes are expressed in byte (or multiples) and not in bytes (or multiple) per second

**Comment by karthik-sethuraman** [comment]
Notes from the 12/27 ad-hoc call to resolve TAPI 2.0 last-call comments
- Update the UML model Enum/Datatype *CapacityUnit* with additional enumeration values *TB, GB, MB, KB* that represent the raw-byte-size unit.

**Comment by italobusi** [comment]
The current fix is error-prone: it is possible to specify rates in byte (or multiples) and/or burst size in bytes (or multiple) per second.

What is the expected behavior in such a case?

Rates must be specified in bytes (or multiple) per second and burst sizes must be specified in byte (or multiples).

I think it would be much cleaner and simpler to have different types for rate and burst size attributes
