### ISSUE TITLE
Need for Context UUID and Name

### ISSUE THREAD

**Issue by italobusi** [OpenNetworkingFoundation/TAPI#277]
The Context object class as a uuid and a name attribute

It is not clear why we need this attribute since the context is the root of all the TAPI objects.

Even if needed, it is also not clear why the writeAllowed stereotype is CREATE_AND_UPDATE instead of WRITE_NOT_ALLOWED.

In YANG, these attributes have been translated as rw (but they should be ro):

```
       +--rw uuid?                      uuid
       +--rw name* [value-name]
          +--rw value-name    string
          +--rw value?        string

```

I do not think the TAPI context can be created/deleted.

**Comment by amazzini** [comment]
This issue has been closed due to the lack of activity for more than one year.
Please reopen it if follow up is necessary.
