### ISSUE TITLE
Syntax of the costName attribute for the CostCharacteristic DataType

### ISSUE THREAD

**Issue by italobusi** [OpenNetworkingFoundation/TAPI#278]
I have some concerns about how multi-vendor interoperability can be achieved if the costName attribute syntax is defined as a String.

How can the TAPI client and TAPI server use the same value to represent the same metric? For example, some implementation may use the name "delay" and other the term "latency" to call the same metric. 

How can a TAPI client interested into a delay/latency metric know which name has been used by the server? Should the TAPI client know all the possible string values that may be assigned to that metric?

Moreover, even if the costName attribute is the same, the associated semantics (e.g., the measurement unit) can be different. For example, the same metric "distance" may be provided in Km or in miles. How can the TAPI client know what is the right semantic of a given metric provided by the server?

IMHO, the syntax of the costName attribute should be an extensible enumeration where, for each value of the enumeration, a precise definition of the associated metric is defined.

**Comment by amazzini** [comment]
This issue has been closed due to the lack of activity for more than one year.
Please reopen it if follow up is necessary.
