### ISSUE TITLE
Clarification on the costAlgorithm attribute of the CostCharacteristic DataType

### ISSUE THREAD

**Issue by italobusi** [OpenNetworkingFoundation/TAPI#280]
This attribute is not fully clear

The UML definition is self referencing:

> The cost may vary based upon some properties of the TopologicalEntity. The rules for the variation are conveyed by the costAlgorithm.

**Comment by amazzini** [comment]
This issue has been closed due to the lack of activity for more than one year.
Please reopen it if follow up is necessary.
