### ISSUE TITLE
YANG NMDA Strategy

### ISSUE THREAD

**Issue by italobusi** [OpenNetworkingFoundation/TAPI#283]
YANG data store architecture, as defined by IETF Netmod WG, is evolving

It is not clear how TAPI 2.0 YANG models would transition towards NMDA compliancy

Guidelines for NMDA transitions are defined in section 4.23.3 of https://tools.ietf.org/html/draft-ietf-netmod-rfc6087bis

I think the NMDA transition strategy needs to be defined before TAPI 2.0 is released

**Comment by amazzini** [comment]
This issue has been closed due to the lack of activity for more than one year.
Please reopen it if follow up is necessary.
