### ISSUE TITLE
cs1.json referenced in the tapi-client.sh is missing in the project space:

### ISSUE THREAD

**Issue by ManoharSL** [OpenNetworkingFoundation/TAPI#307]
In the TAPI_RI/python_client/tapi-client.sh, there is a reference to the cs1.json file for the
"Create Connectivity Service" Request. But this file is not available in the directory.

Commit this file in the python_client directory space.

**Comment by ManoharSL** [comment]
It would greatly help testing Connectivity-Service with SNOWMASS, if the cs1.json can be made available.

**Comment by abubakarmuqaddas** [comment]
Hi, can the cs1.json file be shared to test the connectivity service?

**Comment by amazzini** [comment]
This issue has been closed due to the lack of activity for more than one year.
Please reopen it if follow up is necessary.
