### ISSUE TITLE
Multi-layer NEP

### ISSUE THREAD

**Issue by amazzini** [OpenNetworkingFoundation/TAPI#309]
There are cases where a port of a device can support different layer rates, e.g. both DSR/CBR and ODU (i.e. transport of not-terminated ODU container). Current definition of SIP allows more LayerProtocolName to be specified, while NEP foresees only one  LayerProtocolName. To facilitate the mapping of device port with NEP, we may consider to allow multi-layer NEPs.

**Comment by italobusi** [comment]
It seems we are assuming that a NEP can multi-layer

In this case, we need to reconcile this with the outcome of the discussion of open issue #145

**Comment by amazzini** [comment]
This issue has been closed due to the lack of activity for more than one year.
Please reopen it if follow up is necessary.
