### ISSUE TITLE
ProtectionType includes also "restoration" types

### ISSUE THREAD

**Issue by amazzini** [OpenNetworkingFoundation/TAPI#310]
The attribute resilienceType has type ResilienceType, which is structured into restorationPolicy and protectionType owned attributes. The attribute protectionType has type ProtectionType, which is an enumeration of literals which mixes "protection" and "restoration" types. We may consider to split the protectionType attribute into two attributes, e.g. protectionType and restorationType.

**Comment by karthik-sethuraman** [comment]
Fixed as part of PR #379
