### ISSUE TITLE
TAPI Ethernet: EthCtpPac/vlanConfig

### ISSUE THREAD

**Issue by amazzini** [OpenNetworkingFoundation/TAPI#313]
The vlanConfig attribute of EthCtpPac should be a table, rather than a single integer. Same comment applies to G.8052-v2.03, where the VlanConfigSink/Source_Pac foresee single integer, and are referenced by ETH_ConnectionTerminationPointSink/Source with multiplicity 0..1

**Comment by bzeuner** [comment]
G.8021 defines the MI_VLAN_Config as a list [1...M]. [1...M] is identifying the list of client Ethernet CTPs. The VlanConfigSink/Source_Pac is associated to such a client Ethernet CTP which means that there is **only one** MI_VLAN_Config per CTP.

G.8021 defines for So_MI_VLAN_Config: _"The MI_VLAN_Config input parameter determines for every input port the associated VID value. The allowed values for the VID signal are untagged, priority tagged and 1-4094."_
G.8021 defines for Sk_MI_VLAN_Config: _"The MI_Vlan_Config parameter specifies the possible VID values for the ports to be used. If there is no port assigned to a specific VID value and this VID value is used, the VID Demux process will filter the incoming signal set.
Disabling the ingress VID filtering is modelled by setting MI_Vlan_Config [1…4094]. "_

Therefore, the vlanConfig need to be a single attribute which could have the following values:

- untagged
- priority tagged
- 1-4094 (also non adjacent ranges like 10..20 | 100..120 | 200)

**Comment by bzeuner** [comment]
The VLAN_Config parameter is defined for the VLAN bundling case
- ETHx/ETHG_A_So_MI_VLAN_Config[1...M]
- ETHx/ETHG_A_Sk_MI_VLAN_Config[1...M]

**and also** for the "normal" VLAN multiplexing case
- ETHx/ETH-m_A_So_MI_VLAN_Config[1...M]
- ETHx/ETH-m_A_Sk_MI_VLAN_Config[1...M]

**Comment by amazzini** [comment]
MEF 10.3: "Bundling Enabled is compatible with Service Multiplexing". Hence I would recommend to model one connection. May G.8052 represent a G.8021 ETHG as single CTP?

**Comment by italobusi** [comment]
@bzeuner : The current definition of the ETHx/ETHG_A in G.8021 is not fully clear to me. At the first glance I do not see differences between the ETHx/ETH-m_A and the ETHx/ETHG_A atomic functions.
Let's have some check with ITU-T experts

**Comment by amazzini** [comment]
@italobusi 
Because the subject is a network management model - hence for management perspective, there is no rationale to model a "bundle" of connections.

**Comment by karthik-sethuraman** [comment]
TAPI Call April 17, 2018
![image](https://user-images.githubusercontent.com/1877698/38876253-2315f4f4-422a-11e8-8eb7-cecd3042a9ef.png)

**Comment by amazzini** [comment]
This issue has been closed due to the lack of activity for more than one year.
Please reopen it if follow up is necessary.
