### ISSUE TITLE
Clarification regarding connection's route contents

### ISSUE THREAD

**Issue by antoniofelix** [OpenNetworkingFoundation/TAPI#315]
According to the TAPI model a connection's route contains the CEP that are used to implement the connectivity in the network.
In multilayer scenarios a low order connection might be carried by high order connections (odu2 -> odu4 -> otsi). 
Question: which CEP shall be considered for the low order connection? 
Option 1) The CEP that implement the odu2 layer only? 
The issue with this approach is that in some cases the route contents are always the same regardless of the effective route of the server odu4 or otsi connections. Other issue is that a TAPI client must drill down all the hierarchy in order to obtain a topological view of the route.
Option 2) All the CEP through which the low order connection traverses, i.e, the odu2, odu4, otsi CEP?
This approach mixes details of different layers (odu4, otsi CEP referenced within odu2 route) but clearly shows how and where the routes are different. The topological drill down is a task for the TAPI server.

**Comment by amazzini** [comment]
Clarifications provided in TR-547 v1.1 on.
