### ISSUE TITLE
Missing path constrains into tapi-path-computation model

### ISSUE THREAD

**Issue by arthurMll** [OpenNetworkingFoundation/TAPI#333]
According to my latest review of tapi-path-computation model, there are some parameters already included in tapi-connectivity model regarding the introduction of path constrains which are currently missing.

My general comment is that all path constrians which are available in tapi-connectivity model shall be availabe for the path computation service. Nevertheless its possible that some cases may differ, so I leave here what I consider are missing now within the "routing-constraint" container:

- diversity-exclusion
- exclude-path
- include-path
- include-link
- exclude-link
- include-node
- diversity-policy
- exclude-node

**Comment by italobusi** [comment]
You can also take a look at this document:

https://tools.ietf.org/html/draft-ietf-teas-yang-path-computation-02

We have started the work from TAPI path computation and further improved it based on feedbacks/comments from TE experts in IETF

In particular, it highlights the importance of having alignment between path computation and connectivity setup path constraints

My 2 cents

Italo

**Comment by karthik-sethuraman** [comment]
@arthurMll I will update it today to align with the Connectivity model.

**Comment by openflow-lyo** [comment]
Thanks, Italo.


________________________________
