### ISSUE TITLE
Bulk request for multiple simulateneous path computations

### ISSUE THREAD

**Issue by arthurMll** [OpenNetworkingFoundation/TAPI#342]
Hi,

I was reviewing the tapi-path-computation model to evaluate if it is currently possible to request multiple path computations between two service endpoints (i.e., the computation of the working and protection paths for a given service simultaneously), but I think it is not currently possible.

Is there a plan to support this use case in the future?

Thanks,

**Comment by amazzini** [comment]
Still in the plan for version 2.6.0
