### ISSUE TITLE
OIF Demo Finding #3 - Restoration Controls

### ISSUE THREAD

**Issue by openflow-lyo** [OpenNetworkingFoundation/TAPI#344]
Issue Title
- Restoration controls
Description
- Need to add   restoration operational controls
Discussion
- The OIF has previously   defined operational controls for reroute (See OIF-ENNI-REC-AM-01.0).  These include: Forced Restoration,   Restoration Freeze, Make Permanent.  In   addition, customers need to be able to schedule when reversion takes place.   These are not provided in the TAPI specification.
Resolution (Demo)
- Reroute did not provide any restoration controls
Resolution (Long   Term)
 -          open for contribution, add to github list  
 -          multilevel hierarchy of SDN controllers may   need additional work

**Comment by amazzini** [comment]
This issue has been closed due to the lack of activity for more than one year.
Please reopen it if follow up is necessary.
