### ISSUE TITLE
OIF Demo Finding #6 - Need for additional result codes

### ISSUE THREAD

**Issue by openflow-lyo** [OpenNetworkingFoundation/TAPI#345]
Issue Title
- HTTP result codes are not descriptive enough |  
Description
- The HTTP result codes (e.g. 40x) do not provide enough   information about the API server’s disposition of a request |  
Discussion
- Without more explicit result codes, or a verbose reason string,   it is hard to debug across the API.
May want to look at ONAP VES
Resolution (Demo)
-  General behavior should be respond with a 4xx when a failure is   known (e.g. if path computation fails).    Specific 4xx is not specified at this time but should be as a part of   long term work.  
Resolution (Long Term)
 -          open issue on this – needs further work – request Jack to   provide information/proposal, e.g., based on ONAP VES work

**Comment by amazzini** [comment]
This issue has been closed due to the lack of activity for more than one year.
Please reopen it if follow up is necessary.
