### ISSUE TITLE
OIF Demo Finding #9 - automated neighbor discovery

### ISSUE THREAD

**Issue by openflow-lyo** [OpenNetworkingFoundation/TAPI#346]
Issue Title
- No   automated way to establish I-/E-NNI links
Description
- Having   a link between two domains appear in the orchestrator’s topology requires   configuration in the orchestrator.    This has the possibility of introducing work errors.
Discussion
- Having   an automated/semi-automated way to establish E-NNI links is desirable.
OIF’s Neighbor Discovery IA (See OIF-ND-IA-01.0) may provide a method to automate auto-discovery of E-NNI   links.  To use this method, the TAPI   spec needs to be extended to enable configuration of in-band discovery   trigger messages.   Alternatively, endpoints could be “tagged” allowing the orchestrator   to correlate two ends of an I-/E-NNI link.
Resolution (Demo)
- No change to specifications.
Resolution (Long   Term)
 -          would be very useful – need to look at any   TAPI impacts to support this if available = need contributions – should be if   possible independent of the mechanism used for discovery

**Comment by amazzini** [comment]
Solved by Plug Id since version 2.1.3
