### ISSUE TITLE
TAPI YANG Augments are missing a corresponding YANG Data Node

### ISSUE THREAD

**Issue by amazzini** [OpenNetworkingFoundation/TAPI#356]
For example, TAPI YANG currently generates the following TAPI OAM Augment:
```
    augment "/tapi-common:context/tapi-oam:oam-job" {
        uses eth-link-trace-job;
        description "none";
    }
```
This makes it impossible to further augment the augmenting node (eth-link-trace-job), as necessary e.g. from MEF NRM-OAM model. It is recommended to insert a wrapping YANG _container_ for the YANG _uses_ statement, as below shown:
```
    augment "/tapi-common:context/tapi-oam:oam-job" {
        container eth-link-trace-job {
          uses eth-link-trace-job;
        }
        description "none";
    }
```

**Comment by italobusi** [comment]
That's depend on how the grouping (e.g., the eth-link-trace-job grouping) is defined

If the container (e.g., container eth-link-trace-job) is defined within the grouping, the current augmentation statements will be ok

**Comment by karthik-sethuraman** [comment]
The Eagle Uml2Yang tool and mapping guidelines have all _classes_ directly mapped to YANG _groupings_. And the _grouping_ is wrapped with either a _list_ or a _container_ statement when an instance of the class is contained within another class (as an composed attribute). So no further is _container_ defined within _grouping_ as it would create unnecessary level of _containers_. 
So changes will be more localized if a wrapper _container_ is created just in case of the _augment_ statements,
