### ISSUE TITLE
Backward compatibility clarification

### ISSUE THREAD

**Issue by italobusi** [OpenNetworkingFoundation/TAPI#358]
As agreed in the IMP call on September 27, 2018, backward compatibility issues (e.g. issue #282) will not be addressed in R2.1 but in a future release and the status will be reported in R2.1 release notes:

https://wiki.opennetworking.org/display/OIMT/2018-09-27+OIMT+Meeting+Notes

**Comment by italobusi** [comment]
Initial proposed text for TAPI 2.1 release note:

> ONF TAPI release process does not guarantee backward compatibility among different TAPI versions
> 
> TAPI R2.1 models are not backward compatible with previous TAPI releases (e.g., R2.0.2). There is no guarantee that the next TAPI release (e.g., R2.1.1) will be backward compatible with R2.1
> 
> It is expected that backward compatibility issues will be addressed by ONF for further releases

**Comment by italobusi** [comment]
Better to reference the RFC7950 instead of RFC6020:

> ONF TAPI release process does not guarantee backward compatibility of YANG models, as outline in section 10 of https://tools.ietf.org/html/rfc7950, among different TAPI major versions
> 
> TAPI R2.1 YANG models are not backward compatible with previous TAPI releases (e.g., R2.0.2)

**Comment by karthik-sethuraman** [comment]
As per the TAPI call on 10/2/18 (https://wiki.opennetworking.org/display/OTCC/2018-10-02+TAPI+Meeting+Notes), I would propose the following text
```
- ONF TAPI release process does not guarantee backward compatibility of YANG models across major versions of TAPI releases. The Yang model backward compatibility criteria is outlined in section 10 of (https://tools.ietf.org/html/rfc7950) 
- TAPI R2.1 YANG models are not backward compatible with previous TAPI releases
```
