### ISSUE TITLE
TAPI 2.1 PHOTONIC_LAYER_QUALIFIER_SMC

### ISSUE THREAD

**Issue by sergiobelotti** [OpenNetworkingFoundation/TAPI#364]
In the TAPI 2.1 model , I noticed that while there is no any “Service Media Channel” artifact defined , ittwo specific qualifier have been defined  PHOTONIC_LAYER_QUALIFIER_SMC and PHOTONIC_LAYER_QUALIFIER_SMCA. 
That would permit to create a wide Media Channel and at the same time its inner Media Channels (NMC).
I think that we are still on discussion on the acceptance of the concept of wide Media Channel , ITU as well was not accepted last meeting the introduction of this specialization of FC see https://www.itu.int/md/T17-SG15-181008-TD-WP3-0254 Annex 5,
"“The concept of a wide media channel”: We are currently planning to use a forwarding construct to represent a media channel. The properties will describe its end points (FC ports) the centre frequency and width. We do not see the need to define a new specialization of the FC to represent a “wide” media channel....." 
for this couple of reasons I do not see any reason to have these qualifiers defined in the contenxt of TAPI 2.1.
In the view of LC to released TAPI 2.1 I would propose and suggest to delete these qualifiers .

**Comment by sslsangi** [comment]
In an optical network, media channel are created by the concatenation of filter. SMC are there to represent programmable or fixe filter (the media channel that is created at a node level). NMC are there to represent the intent of the location of the signal so the optical layer have enough information to measure the associated power when the intent is realized by placing a signal into that specific spectrum location at the edge of the optical network. The Service Media Channel is a filter, the media channel that is created at every node. By concatenating them at the network level, then we obtain a media channel. By defining a SMC of 100 GHz at the same spectrum location at all the node of the route that is planned to use, then we have created a 100GHz media channel that could be used to pass signal. It the user decide to pass two 33 GHz signal through this 100 GHz media channel, then it tell the optical layer that this SMC contain 2 NMC of 33 GHz at a specific location inside that SMC.

A forwarding construct in the Photonic layer, in CIM, is a media channel define by a filter with a layer protocol qualifier (OTS,OMS,SMC, NMC)

**Comment by karthik-sethuraman** [comment]
Fixed by #410 and agreements in related discussions in TAPI F2F meetings @sunnyvale, @sydney and Tapi calls. The notes capture these conclusions/results:

https://wiki.opennetworking.org/pages/viewpage.action?pageId=371654692
https://wiki.opennetworking.org/pages/viewpage.action?pageId=414515202
https://wiki.opennetworking.org/display/OTCC/2019-04-02+TAPI+Meeting+Notes
