### ISSUE TITLE
erroneous container in tapi-photonic-media yang model

### ISSUE THREAD

**Issue by Andrea-Campanella** [OpenNetworkingFoundation/TAPI#386]
I generated the following tree (see figure down the mail) from yang git.  Branch develop, yang files 2018-12-10.

To create a connectivity service:  

I) For OTSi, I can see that for each end-point, 

- there is a tapi-photonic-media:otsi-connectivity-service-end-point-spec

- within that container, there is a otsi-config container.

- I can specify the central-frequency, spectrum and application identifier.

- (Out of otsi-config) I can set the modulation and laser control, and transmit power.

II) Now, for Media Channel, trying to mimic OTSI...

- There is tapi-photonic-media:media-channel-service-interface-point-spec . I wondered why it is  named service-interface-point spec and not media-channel-connectivity-service-end-point-spec

- There is a mc-pool, shouldn't it be mc-config?

- In mc-config (it does not make sense to have supportable, available, occupied) I should provide upper and lower . Most data is non-config.

I am guessing there may be an issue. Taking a look at Yang, IMHO, this is not "right"

  
diff --git a/YANG/tapi-photonic-media@2018-12-10.yang b/YANG/tapi-photonic-media@2018-12-10.yang
index dc69c76..1936dd3 100755
--- a/YANG/tapi-photonic-media@2018-12-10.yang
+++ b/YANG/tapi-photonic-media@2018-12-10.yang
@@ -109,8 +109,8 @@ module tapi-photonic-media {
         description "none";
     }
     augment "/tapi-common:context/tapi-connectivity:connectivity-context/tapi-connectivity:connectivity-service/tapi-connectivity:end-point" {
-        container media-channel-service-interface-point-spec {
-            uses media-channel-service-interface-point-spec;
+        container media-channel-connectivity-service-end-point-spec {^M
+            uses media-channel-connectivity-service-end-point-spec;^M
             description "none";
         }
         description "none";    

With this change, the tree seems correct and I can have

      "end-point" : [
         {
            "local-id" : "00000000-0000-0000-0001-000000000001",
            "layer-protocol-name" : "PHOTONIC_MEDIA",
            "layer-protocol-qualifier" : "tapi-photonic-media:PHOTONIC_LAYER_QUALIFIER_NMC",
            "service-interface-point" : {
               "service-interface-point-uuid" : "00000000-0000-0000-0001-000000000001"
            },
            "tapi-photonic-media:media-channel-connectivity-endpoint-spec" : {
                "tapi-photonic-media:mc-config" : {
                    "tapi-photonic-media:spectrum" : {
                        "upper-frequency" : 1,
                        "lower-frequency" : 2,
                        "frequency-constraint" : {
                            "adjustment-granularity" : "G_6_25GHZ",
                            "grid-type": "FLEX"
                        }
                    }
                }
            }

         },

Thanks for the contribution to Ramon Casellas

**Comment by karthik-sethuraman** [comment]
Fixed as part of #353 and #408

**Comment by arthurMll** [comment]
This bug was not fixed in TAPI v2.1, could it be push a change to v2.1-bug-fixes version?

**Comment by amazzini** [comment]
This issue has been closed due to the lack of activity for more than one year.
Please reopen it if follow up is necessary.
