### ISSUE TITLE
Typo error in the enumeration of protection-type in tapi-topology.yang 

### ISSUE THREAD

**Issue by tqhuy812** [OpenNetworkingFoundation/TAPI#390]
https://github.com/OpenNetworkingFoundation/TAPI/blob/f1d17ce7418ed5b601f15815edf413016dc04754/YANG/tapi-topology%402018-12-10.yang#L602

Should be NO_PROTECTION (missing letter "I"). This error appears in both master and develop branches.

**Comment by amazzini** [comment]
The bug regards 2.1 model. The enumeration has been changed for 2.2, with correct wording.
