### ISSUE TITLE
OAS Document Structure

### ISSUE THREAD

**Issue by damianoneill** [OpenNetworkingFoundation/TAPI#392]
Per [OAS Document Structure definition](https://github.com/OAI/OpenAPI-Specification/blob/master/versions/3.0.0.md#document-structure) can the OAS output be updated to include a root document, openapi.yaml that includes the multiple documents that are generated in [OAS](https://github.com/OpenNetworkingFoundation/TAPI/tree/develop/OAS)

**Comment by amazzini** [comment]
The multiple generated documents are described in the script https://github.com/OpenNetworkingFoundation/TAPI/blob/develop_v2_1/YANG/yang2oas213.txt used for OAS generation, where the dependencies between YANG modules are specified.
There are two important aspects:
1) The order in which YANG modules are listed, which specifies the dependencies between modules.
2) The last YANG module in the row becomes the generated YAML module, e.g.

    [6]='tapi-common tapi-notification tapi-topology tapi-path-computation tapi-connectivity'

generates the tapi-connectivity.yaml file.
