### ISSUE TITLE
OSNR Monitoring 

### ISSUE THREAD

**Issue by arthurMll** [OpenNetworkingFoundation/TAPI#402]
Following ip the model enhancements proposed in #353 and #393 , I would like to open the discussion for the introduction of the OSNR as the key performance metric for optical signal integrity validation within the photonic-media model.

The main use case is the validation of an OTSi service when the management of the OTSi and OTSiMC is split between to entities. In this scenario (partial optical disaggregation), it is desirable that the Open Line System (OLS) controller entity can export via TAPI the OSNR monitored values associated to the OTSiMC spectrum band at different points of the channel path.

Please find more detailed information about this proposal at the TAPI wiki page:
https://wiki.opennetworking.org/download/attachments/259719184/TAPI-UC%20OSNR-Monitoring.pptx?api=v2

**Comment by amazzini** [comment]
Photonic OAM under refinement from 2.5.0
