### ISSUE TITLE
OTSI SIP spec

### ISSUE THREAD

**Issue by arthurMll** [OpenNetworkingFoundation/TAPI#429]
Hi, 

I have a doupt regarding current otsi-service-interface-point-spec:

![imagen](https://user-images.githubusercontent.com/10529210/58951731-2bb88a00-8792-11e9-855b-17167f18f603.png)

It is not clear to me which information is being provided by this spec. What I would expect is a frequency grid that defines the possible set of central frequencies that are available for being configured, but currently, there are **two** different lists for specifying central frequencies.

Could anyone help me to understand current definition?, I am sure it makes sense but I am not able to figure it out.

**Comment by karthik-sethuraman** [comment]
Discussed following contribution on TAPI call on June 25, 2019:
https://wiki.opennetworking.org/download/attachments/259719184/otcc.2019.AMLL.01.00_TAPI_Issue_%23429.pptx?api=v2

**Comment by arthurMll** [comment]
To be fixed also in v2.1.2
