### ISSUE TITLE
Problem with autogeneration of code from the OAS

### ISSUE THREAD

**Issue by damianoneill** [OpenNetworkingFoundation/TAPI#430]
As an example, https://github.com/OpenNetworkingFoundation/TAPI/blob/develop/OAS/tapi-connectivity%402018-12-10.yaml#L10460, when passed through a third party SDK generator such as https://github.com/go-swagger/go-swagger, will fail to generate a valid sdk as the tool generator uses the labels in the oas definition to create named go files.  The length of the generated file cannot be saved to the filesystem.  See below.

```sh
failed to write file "get_data_context_topology_context_topology_uuid_node_node_uuid_owned_node_edge_point_owned_node_edge_point_uuid_cep_list_connection_end_point_connection_end_point_uuid_aggregated_connection_end_point_topology_uuid_aggregated_connection_end_point_node_uuid_node_edge_point_uuid_aggregated_connection_end_point_connection_end_point_uuid_parameters.go" in "restapi/operations/tapi_connectivity": open restapi/operations/tapi_connectivity/get_data_context_topology_context_topology_uuid_node_node_uuid_owned_node_edge_point_owned_node_edge_point_uuid_cep_list_connection_end_point_connection_end_point_uuid_aggregated_connection_end_point_topology_uuid_aggregated_connection_end_point_node_uuid_node_edge_point_uuid_aggregated_connection_end_point_connection_end_point_uuid_parameters.go: file name too long
``` 

I accept this maybe tooling specific, but given the objective of the OAS is to simplify the integration between multi-vendor platforms through API generation and go-swagger is the primary tool for golang sdk generation for OAS ... 

Thanks,
Damian.

**Comment by amazzini** [comment]
This issue has been closed due to the lack of activity for more than one year.
Please reopen it if follow up is necessary.
