### ISSUE TITLE
Ordered Route’s connection-end-points 

### ISSUE THREAD

**Issue by arthurMll** [OpenNetworkingFoundation/TAPI#431]
- Currently the connection/route/ connection-end-point list is (by default) modelled in YANG as ordered-by-system. 

- Someone could argue that the system is not responsible of maintaining a logical order of CEPs.

- Is there any convention of the order that it should be maintained by the TAPI server for connection/route/ connection-end-point elements? E.g., Telefonica has defined within its specification:

> _The server is responsible of maintaining an ordered list starting from the CEP associated to the NEP associated to the SIP element included in the first element of the tapi-connectivity:connectivity-service/end-point list, and terminating into the CEP associated to the NEP associated to the SIP element included in the last element of the same list. The order of CEPs between these two must follow the routing path selected by the service across the layer. Apply this rule only on those CSs between two CSEPs._

- Is there any plans of standardizing this behaviour from the TAPI perspective?

**Comment by arthurMll** [comment]
As discussed in the TAPI Call on 11/06/2019, the current approach is that the logical order of the connection-end-points within the Route object can be inferred by the TAPI client by the knowledge of the Topology information.
In order words, it is not assumed that the TAPI server MUST maintain any logical order or that any additional tag to represent this order will be added in TAPI.

**Comment by italobusi** [comment]
@arthurMll : my understanding is that the TAPI client is not required to maintain any logical order by it may decide to do so. In any case the client will not know and cannot assume any order.
Is my understanding correct?

**Comment by arthurMll** [comment]
@italobusi : I think there is a typo in your statement:

> my understanding is that the TAPI **client**...

I think you refer to TAPI server.

Nevertheless, my understanding is the same as yours: the  TAPI server is not required to maintain any logical order by it may decide to do so. The underlying assumption is that the topology information associated to the CEPs referred in the Route object, exposed by the TAPI server MUST be sufficient to infer the topological path of the related connection, for visualization or any other purposes.
