### ISSUE TITLE
Connectivity Service Creation - "name" attribute not provisionable

### ISSUE THREAD

**Issue by amazzini** [OpenNetworkingFoundation/TAPI#433]
Currently the Connectivity Service creation and update operations do not foresee the provisioning of "name" attribute. This would be useful on Client side.

**Comment by amazzini** [comment]
Decision on TAPI call (25 June 2019): Agreed to add "name" as input parameter of ALL create and update RPCs (ConnectivityService, OamService, OamProfile, OamJob, PathService).

**Comment by italobusi** [comment]
To which version? 2.2, 2.1.2, 3.0?
