### ISSUE TITLE
Connectivity Service Creation - "layerProtocolName" attribute not provisionable

### ISSUE THREAD

**Issue by amazzini** [OpenNetworkingFoundation/TAPI#434]
Currently the Connectivity Service creation and update operations do not foresee the provisioning of "layerProtocolName" attribute. This information is expected to be provisioned on CSEPs. In case of
- symmetric scenario, all CSEPs share same layerProtocolName value,
- asymmetric scenario, CSEPs may have different layerProtocolName values.
In the asymmetric case, is it assumed that ConnectivityService layerProtocolName value is the client-most of listed CSEP ones?
It is possible to specify CSEPs of encapsulated layers (using the CSEPHasServerCSEP association, e.g. showing ODU0 CSEP on ODU2 unterminated trail), but to my knowledge there is no specific rule to always specify all client-most CSEPs.

**Comment by amazzini** [comment]
Noted that "layerProtocolName" was defined in ConnectivityConstraint class as "serviceLayer" attribute, in version 2.1.1

**Comment by amazzini** [comment]
Decision on TAPI call (25 June 2019): Agreed to add layerProtocolName as input parameter of create RPC.

**Comment by italobusi** [comment]
In which version? 2.2, 2.1.2, 3.0?
