### ISSUE TITLE
ConnectivityService, "direction" attribute.

### ISSUE THREAD

**Issue by amazzini** [OpenNetworkingFoundation/TAPI#435]
The CS "direction" attribute type is an enum {BIDIRECTIONAL, UNIDIRECTIONAL, UNDEFINED_OR_UNKNOWN}. Currently is not possible to provision this attribute, hence it may be assumed that CS forwarding direction is driven by its CSEPs direction attribute values: PortDirection, enum {BIDIRECTIONAL, INPUT, OUTPUT, UNIDENTIFIED_OR_UNKNOWN}.
If the assumption is correct, the CS "direction" attribute seems redundant.

**Comment by amazzini** [comment]
Decision on TAPI call (25 June 2019): Agreed to remove it in version 3.x to avoid backward compatibility issue.

**Comment by italobusi** [comment]
What about R2.1.2?

**Comment by karthik-sethuraman** [comment]
> What about R2.1.2?

No change for that
