### ISSUE TITLE
Distiction between backup and nominal routes

### ISSUE THREAD

**Issue by arthurMll** [OpenNetworkingFoundation/TAPI#436]
Currently there is not distinction between which is the "Nominal" or "Primary" route and the rest of backup routes, for a given connection.
There are more than one point to tackle here:
    1. Currently in TAPI, the “tapi-connectivity:connection/switch-control/switch/selected-route” object, is the data node in TAPI designed to specify which is  the active route for a given connection which implements the switch control between two lower-level connections. Is this assumption correct?
    2. The route object does not contain any attribute which may help to identify it as the nominal or primary route for a given connection. E.g., in case of a restorable service has changed its original (nominal or primary route), there not a way in TAPI to revert manually that connection to its original route.

**Comment by arthurMll** [comment]
Already discussed during TAPI call 25/06/2019, the overall idea is that the **concept of nominal or primary route for a given connection is not modeled in TAPI yet.**

Regarding (1), the assumption is correct, currently defined "tapi-connectivity:connection/switch-control/switch/selected-route” object is intended to represent only the current active route for a given connection.
Thus, the discussion from now and on is regarding the required new definitions in TAPI required to support new use cases which required this distinction between the nominal route and the backup paths.

**Comment by amazzini** [comment]
Solved from version 2.3.1 on.
