### ISSUE TITLE
Problem with Docker run

### ISSUE THREAD

**Issue by raycola** [OpenNetworkingFoundation/TAPI#447]
Hi,
the docker container doesn't start. 

The image was created successfully. 
-- 7f4f59924363 IMAGE ID

Command:
$docker run -p 8080:8080 7f4f59924363

Output:
  File "/bin/sh", line 1
SyntaxError: Non-UTF-8 code starting with '\x85' in file /bin/sh on line 2, but no encoding declared; see http://python.org/dev/peps/pep-0263/ for details

Inspection info:
$docker inspect 7f4f59924363

Output (Omitted with ....)
[
    {
        "Id": "sha256:...",
        "RepoTags": [
            "docker-registry....",
            ".....-1.0.0"
        ],
        "RepoDigests": [
            "docker-registry.....tapiserver@sha256:...."
        ],
        "Parent": "sha256:......",
        "Comment": "",
        "Created": "2019-07-23T08:48:57.115206414Z",
        "Container": "1aee.....",
        "ContainerConfig": {
            "Hostname": "0e....",
            "Domainname": "",
            "User": "",
            "AttachStdin": false,
            "AttachStdout": false,
            "AttachStderr": false,
            "ExposedPorts": {
                "8080/tcp": {}
            },
            "Tty": false,
            "OpenStdin": false,
            "StdinOnce": false,
            "Env": [
                "PATH=/usr/local/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/u                                                                                                             sr/bin:/sbin:/bin",
                "LANG=C.UTF-8",
                "GPG_KEY=0D.....",
                "PYTHON_VERSION=3.7.4",
                "PYTHON_PIP_VERSION=19.1.1"
            ],
            "Cmd": [
                "/bin/sh",
                "-c",
                "#(nop) ",
                "CMD [\"/bin/sh\" \"-c\" \"[\\\"-m\\\", \\\"tapi_server\\\" \\\"                                                                                                             8080\\\" \\\"tpnd\\\"]\"]"
            ],
            "ArgsEscaped": true,
            "Image": "sha256:d6......",
            "Volumes": null,
            "WorkingDir": "/usr/src/app",
            "Entrypoint": [
                "python3"
            ],
            "OnBuild": [],
            "Labels": {}
        },
        "DockerVersion": "1.13.1",
        "Author": "",
        "Config": {
            "Hostname": "0e...",
            "Domainname": "",
            "User": "",
            "AttachStdin": false,
            "AttachStdout": false,
            "AttachStderr": false,
            "ExposedPorts": {
                "8080/tcp": {}
            },
            "Tty": false,
            "OpenStdin": false,
            "StdinOnce": false,
            "Env": [
                "PATH=/usr/local/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/u                                                                                                             sr/bin:/sbin:/bin",
                "LANG=C.UTF-8",
                "GPG_KEY=0D....",
                "PYTHON_VERSION=3.7.4",
                "PYTHON_PIP_VERSION=19.1.1"
            ],
            "Cmd": [
                "/bin/sh",
                "-c",
                "[\"-m\", \"tapi_server\" \"8080\" \"tpnd\"]"
            ],
            "ArgsEscaped": true,
            "Image": "sha256:d.....",
            "Volumes": null,
            "WorkingDir": "/usr/src/app",
            "Entrypoint": [
                "python3"
            ],
            "OnBuild": [],
            "Labels": {}
        },
        "Architecture": "amd64",
        "Os": "linux",
        "Size": 135980414,
        "VirtualSize": 135980414,
        "GraphDriver": {
            "Name": "overlay2",
            "Data": {
                "LowerDir": "/var/lib/docker/overlay2/75c....",
                "MergedDir": "/var/lib/docker/overlay2/81a....",
                "UpperDir": "/var/lib/docker/overlay2/81a....",
                "WorkDir": "/var/lib/docker/overlay2/81a...."
            }
        },
        "RootFS": {
            "Type": "layers",
            "Layers": [
                "sha256:1b....",
                "sha256:62.....",
                "sha256:c0....",
                "sha256:ad....",
                "sha256:6e....",
                "sha256:40....",
                "sha256:3f.....",
                "sha256:2da......",
                "sha256:31....."
            ]
        }
    }
]

$ docker inspect 7f4f59924363
[
    {
        "Id": "sha256:7f4f599243636c23554b749b3cf8e8012ef3dfb646a85cb1301ac658210a44e1",
        "RepoTags": [
            "docker-registry.default.svc:5000/tim/tim-ngtnm-tapiserver:rhel-1.0.0",
            "tim-ngtnm/tapiserver:rhel-1.0.0"
        ],
        "RepoDigests": [
            "docker-registry.default.svc:5000/tim/tim-ngtnm-tapiserver@sha256:43062c88d69a6ca3e15bb30088faea60cf27f21bfe7ac5a8459c24479e296ed6"
        ],
        "Parent": "sha256:d65dfaa914b053fb10239c5318c69e64aa9b47ba382ef779298e7032646c3e37",
        "Comment": "",
        "Created": "2019-07-23T08:48:57.115206414Z",
        "Container": "1aee713e20a3d7649950e4165b5b4d3062ff2e24ec90376d7184ec3c5962a97f",
        "ContainerConfig": {
            "Hostname": "0e327a3e6da3",
            "Domainname": "",
            "User": "",
            "AttachStdin": false,
            "AttachStdout": false,
            "AttachStderr": false,
            "ExposedPorts": {
                "8080/tcp": {}
            },
            "Tty": false,
            "OpenStdin": false,
            "StdinOnce": false,
            "Env": [
                "PATH=/usr/local/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin",
                "LANG=C.UTF-8",
                "GPG_KEY=0D96DF4D4110E5C43FBFB17F2D347EA6AA65421D",
                "PYTHON_VERSION=3.7.4",
                "PYTHON_PIP_VERSION=19.1.1"
            ],
            "Cmd": [
                "/bin/sh",
                "-c",
                "#(nop) ",
                "CMD [\"/bin/sh\" \"-c\" \"[\\\"-m\\\", \\\"tapi_server\\\" \\\"8080\\\" \\\"tpnd\\\"]\"]"
            ],
            "ArgsEscaped": true,
            "Image": "sha256:d65dfaa914b053fb10239c5318c69e64aa9b47ba382ef779298e7032646c3e37",
            "Volumes": null,
            "WorkingDir": "/usr/src/app",
            "Entrypoint": [
                "python3"
            ],
            "OnBuild": [],
            "Labels": {}
        },
        "DockerVersion": "1.13.1",
        "Author": "",
        "Config": {
            "Hostname": "0e327a3e6da3",
            "Domainname": "",
            "User": "",
            "AttachStdin": false,
            "AttachStdout": false,
            "AttachStderr": false,
            "ExposedPorts": {
                "8080/tcp": {}
            },
            "Tty": false,
            "OpenStdin": false,
            "StdinOnce": false,
            "Env": [
                "PATH=/usr/local/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin",
                "LANG=C.UTF-8",
                "GPG_KEY=0D96DF4D4110E5C43FBFB17F2D347EA6AA65421D",
                "PYTHON_VERSION=3.7.4",
                "PYTHON_PIP_VERSION=19.1.1"
            ],
            "Cmd": [
                "/bin/sh",
                "-c",
                "[\"-m\", \"tapi_server\" \"8080\" \"tpnd\"]"
            ],
            "ArgsEscaped": true,
            "Image": "sha256:d65dfaa914b053fb10239c5318c69e64aa9b47ba382ef779298e7032646c3e37",
            "Volumes": null,
            "WorkingDir": "/usr/src/app",
            "Entrypoint": [
                "python3"
            ],
            "OnBuild": [],
            "Labels": {}
        },
        "Architecture": "amd64",
        "Os": "linux",
        "Size": 135980414,
        "VirtualSize": 135980414,
        "GraphDriver": {
            "Name": "overlay2",
            "Data": {
                "LowerDir": "/var/lib/docker/overlay2/75c72732eeaa9ad4bf71ee5eb45e6fe719240b44c4f8170370c3bb01a38c45e3/diff:/var/lib/docker/overlay2/7a144d19b2ef6dee6bf3e3882268eb6fcdb79e75b9d9b96bc093b5af83532856/diff:/var/lib/docker/overlay2/0998b6236a489f957d53f19ffa09f2b2a1aae75275af88bc84fb235a5f3a5f99/diff:/var/lib/docker/overlay2/e033d772c1bf7c81aeb91f8f1f4d557c0de871b90b3c5c5341528a2a9ddcc61e/diff:/var/lib/docker/overlay2/fd42629b3fbbbfab0c6f1149fa19e710087a87ee236dd25b957dd50bb7c8a284/diff:/var/lib/docker/overlay2/fb98313883f72272682007032c82f3a3a7c52d1268222fff2e2b4320713a8150/diff:/var/lib/docker/overlay2/3a311e414ad588dbdafd99954d6016460147213b8b7b34bc8c03788ba7e3d7f4/diff:/var/lib/docker/overlay2/cfa27db6c57250000fc986e5df2143e86c25d3a4f06338f8db67dd1ee7d3b124/diff",
                "MergedDir": "/var/lib/docker/overlay2/81ac48bad444691b02f1e5e5e04d513a5c6a1a4bdff5743036d94cdd756dc985/merged",
                "UpperDir": "/var/lib/docker/overlay2/81ac48bad444691b02f1e5e5e04d513a5c6a1a4bdff5743036d94cdd756dc985/diff",
                "WorkDir": "/var/lib/docker/overlay2/81ac48bad444691b02f1e5e5e04d513a5c6a1a4bdff5743036d94cdd756dc985/work"
            }
        },
        "RootFS": {
            "Type": "layers",
            "Layers": [
                "sha256:1bfeebd65323b8ddf5bd6a51cc7097b72788bc982e9ab3280d53d3c613adffa7",
                "sha256:622ce7163ec3c52d0c91bc1d71e90918298eb79a629991fc1a0bf5ae9ca06714",
                "sha256:c0519570f3a4b03cb8eb1350e81a2230411e70147452afd12e385bce8517135f",
                "sha256:ad5eb23a8a953a47dd43d2afcbaedb388cbca727da66fc48371e764d16a16598",
                "sha256:6e97aea371c1e4034383c8b4e31c629c18936c450050ecb70edcd004eb8fab83",
                "sha256:40cd5744514f35af471edd5c59ce4eccad2debe47c5e5daceeb12f2ebe48f66b",
                "sha256:3f60bf830d352d27a56c891f46b4315c4a440089beb9d85944e178885f9b3bd1",
                "sha256:2daa185d71e2c1d76d10ea58fa1c5c58baeddc414ac9e0f5aeeb352af77a464a",
                "sha256:31fc758011ebac2d5887c7dbb481d9a770df3edd3c30c90817ea5dd10ad6b15d"
            ]
        }
    }
]

Any suggestions are welcome?

Best Regards
Raimondo Colagrande

**Comment by amazzini** [comment]
This issue has been closed due to the lack of activity for more than one year.
Please reopen it if follow up is necessary.
