### ISSUE TITLE
Should Topology's attribute include node/link references instead of instances?

### ISSUE THREAD

**Issue by HuiDingCATR** [OpenNetworkingFoundation/TAPI#98]
1. Topology object class comprises instances of node and link, should it be just references so the operations can be more efficient. The same with ownedNodeEdgePoint in Node. 

> ```
>     grouping Topology {
>         list _node {
>             key 'uuid';
>             config false;
>             uses Node;
>             description "none";
>         }
>         list _link {
>             key 'uuid';
>             config false;
>             uses Link;
>             description "none";
>         }...}
> ```
1. Node object class

> ```
>     grouping Node {
>         list _ownedNodeEdgePoint {
>             key 'uuid';
>             config false;
>             uses NodeEdgePoint;
>             description "none";
>         }...}
> ```

**Comment by RodLU** [comment]
If turn to reference, the containment relationships may be destroyed. Then the object class like Topology, Node, Link, and NEP wil be paratactic  under Context. I don't know if this will bring bad result, But from implementation perspective, for example, if a Node is deleted in the database of a controller, the controller have to retrieve all the NEPs of this Node, then delete them. On the contrary, this will reduce the efficient.
(This is for your reference only)

**Comment by HuiDingCATR** [comment]
Thanks Rod for the information. For the purpose for the OIF/ONF Interop which will employ TAPI, the parent controller probably only needs getTopologyList and getTopologyDetails to retrieve all the topology information.

**Comment by amazzini** [comment]
This issue has been closed due to the lack of activity for more than one year.
Please reopen it if follow up is necessary.
